# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import Image

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(900, 550)
        MainWindow.setMinimumSize(QtCore.QSize(900, 550))
        MainWindow.setMaximumSize(QtCore.QSize(900, 550))
        MainWindow.setStyleSheet("")
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_5 = QtWidgets.QFrame(self.centralwidget)
        self.frame_5.setGeometry(QtCore.QRect(-10, -30, 961, 21))
        self.frame_5.setStyleSheet("background-color: rgb(12, 141, 81);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 100, 721, 431))
        self.label_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.0852273 rgba(8, 72, 8, 146), stop:0.846591 rgba(0, 90, 0, 192));\n"
"border-radius:10px;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.viewLocatio = QtWidgets.QPushButton(self.centralwidget)
        self.viewLocatio.setGeometry(QtCore.QRect(770, 430, 121, 101))
        self.viewLocatio.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(12)
        self.viewLocatio.setFont(font)
        self.viewLocatio.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.viewLocatio.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.viewLocatio.setStyleSheet("\n"
"\n"
"QPushButton::hover\n"
"{\n"
"background-color: rgb(10, 112, 64);\n"
"};\n"
"\n"
"background-color: rgb(45, 136, 66);\n"
"border-radius: 10px;")
        self.viewLocatio.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img1/locate.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.viewLocatio.setIcon(icon)
        self.viewLocatio.setIconSize(QtCore.QSize(70, 70))
        self.viewLocatio.setAutoDefault(False)
        self.viewLocatio.setDefault(False)
        self.viewLocatio.setFlat(False)
        self.viewLocatio.setObjectName("viewLocatio")
        self.predictImage = QtWidgets.QPushButton(self.centralwidget)
        self.predictImage.setGeometry(QtCore.QRect(770, 320, 121, 101))
        self.predictImage.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(12)
        self.predictImage.setFont(font)
        self.predictImage.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.predictImage.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.predictImage.setStyleSheet("\n"
"QPushButton::hover\n"
"{\n"
"background-color: rgb(10, 112, 64);\n"
"};\n"
"\n"
"background-color: rgb(45, 136, 66);\n"
"border-radius: 10px;")
        self.predictImage.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/img1/classs.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.predictImage.setIcon(icon1)
        self.predictImage.setIconSize(QtCore.QSize(70, 70))
        self.predictImage.setAutoDefault(False)
        self.predictImage.setDefault(False)
        self.predictImage.setFlat(False)
        self.predictImage.setObjectName("predictImage")
        self.InsertImage = QtWidgets.QPushButton(self.centralwidget)
        self.InsertImage.setGeometry(QtCore.QRect(770, 210, 121, 101))
        self.InsertImage.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(12)
        self.InsertImage.setFont(font)
        self.InsertImage.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.InsertImage.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.InsertImage.setStyleSheet("\n"
"QPushButton::hover\n"
"{\n"
"background-color: rgb(10, 112, 64);\n"
"};\n"
"background-color: rgb(45, 136, 66);\n"
"border-radius: 10px;")
        self.InsertImage.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/img1/gallery.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.InsertImage.setIcon(icon2)
        self.InsertImage.setIconSize(QtCore.QSize(70, 70))
        self.InsertImage.setAutoDefault(False)
        self.InsertImage.setDefault(False)
        self.InsertImage.setFlat(False)
        self.InsertImage.setObjectName("InsertImage")
        self.Capture = QtWidgets.QPushButton(self.centralwidget)
        self.Capture.setGeometry(QtCore.QRect(770, 100, 121, 101))
        self.Capture.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(12)
        self.Capture.setFont(font)
        self.Capture.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.Capture.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Capture.setStyleSheet("\n"
"QPushButton::hover\n"
"{\n"
"background-color: rgb(10, 112, 64);\n"
"};\n"
"background-color: rgb(45, 136, 66);\n"
"color: rgb(0, 170, 127);\n"
"color:#9DDABC;\n"
"border-radius: 10px;")
        self.Capture.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/img1/photo-captureD.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Capture.setIcon(icon3)
        self.Capture.setIconSize(QtCore.QSize(70, 70))
        self.Capture.setObjectName("Capture")
        self.label_plantName = QtWidgets.QLabel(self.centralwidget)
        self.label_plantName.setGeometry(QtCore.QRect(210, 81, 301, 41))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Demi")
        font.setPointSize(18)
        self.label_plantName.setFont(font)
        self.label_plantName.setStyleSheet("color: rgb(203, 255, 205);\n"
"background-color: rgb(38, 116, 56);\n"
"border-radius: 5px")
        self.label_plantName.setAlignment(QtCore.Qt.AlignCenter)
        self.label_plantName.setObjectName("label_plantName")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(240, 180, 491, 321))
        self.scrollArea.setAutoFillBackground(False)
        self.scrollArea.setStyleSheet("border-radius:10px;\n"
"background-color:#F2C1E1D1;")
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scrollArea.setLineWidth(0)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 491, 321))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labe_benefits = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.labe_benefits.setFont(font)
        self.labe_benefits.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.labe_benefits.setAutoFillBackground(False)
        self.labe_benefits.setStyleSheet("color: rgb(33, 67, 49);\n"
"bacground-color:#F2C1E1D1;")
        self.labe_benefits.setFrameShape(QtWidgets.QFrame.Box)
        self.labe_benefits.setFrameShadow(QtWidgets.QFrame.Plain)
        self.labe_benefits.setLineWidth(2)
        self.labe_benefits.setText("")
        self.labe_benefits.setScaledContents(False)
        self.labe_benefits.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignTop)
        self.labe_benefits.setWordWrap(True)
        self.labe_benefits.setObjectName("labe_benefits")
        self.verticalLayout.addWidget(self.labe_benefits)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.label_image = QtWidgets.QLabel(self.centralwidget)
        self.label_image.setGeometry(QtCore.QRect(20, 20, 201, 191))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_image.sizePolicy().hasHeightForWidth())
        self.label_image.setSizePolicy(sizePolicy)
        self.label_image.setAutoFillBackground(False)
        self.label_image.setStyleSheet("\n"
"background-color: rgb(38, 116, 56);\n"
"")
        self.label_image.setFrameShape(QtWidgets.QFrame.Box)
        self.label_image.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_image.setLineWidth(1)
        self.label_image.setText("")
        self.label_image.setTextFormat(QtCore.Qt.PlainText)
        self.label_image.setPixmap(QtGui.QPixmap(":/img1/loading_leaf_circle.gif"))
        self.label_image.setScaledContents(True)
        self.label_image.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_image.setWordWrap(True)
        self.label_image.setIndent(20)
        self.label_image.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label_image.setObjectName("label_image")
        self.label_plantName_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_plantName_3.setGeometry(QtCore.QRect(210, 110, 301, 31))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Book")
        font.setPointSize(11)
        self.label_plantName_3.setFont(font)
        self.label_plantName_3.setAutoFillBackground(False)
        self.label_plantName_3.setStyleSheet("color: rgb(203, 255, 205);\n"
"background-color: rgb(10, 112, 64);\n"
"border-radius:10px;")
        self.label_plantName_3.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_plantName_3.setObjectName("label_plantName_3")
        self.label_plantName_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_plantName_4.setGeometry(QtCore.QRect(250, 190, 491, 321))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Book")
        font.setPointSize(12)
        self.label_plantName_4.setFont(font)
        self.label_plantName_4.setAutoFillBackground(False)
        self.label_plantName_4.setStyleSheet("color: rgb(203, 255, 205);\n"
"background-color: rgb(10, 112, 64);\n"
"border-radius:10px;")
        self.label_plantName_4.setText("")
        self.label_plantName_4.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_plantName_4.setObjectName("label_plantName_4")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(60, 55, 831, 21))
        self.frame.setStyleSheet("background-color: rgb(10, 112, 64);\n"
"border-radius:10px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_plantName_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_plantName_2.setGeometry(QtCore.QRect(280, 20, 611, 31))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Demi")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label_plantName_2.setFont(font)
        self.label_plantName_2.setStyleSheet("color: rgb(28, 86, 42);")
        self.label_plantName_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_plantName_2.setObjectName("label_plantName_2")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(160, 30, 111, 16))
        self.frame_2.setStyleSheet("background-color: rgb(10, 112, 64);\n"
"border-radius:3px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(-10, -10, 961, 16))
        self.frame_3.setStyleSheet("background-color: rgb(10, 112, 64);\n"
"border-radius:10px;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_plantName_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_plantName_5.setGeometry(QtCore.QRect(350, 160, 391, 121))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Book")
        font.setPointSize(11)
        self.label_plantName_5.setFont(font)
        self.label_plantName_5.setAutoFillBackground(False)
        self.label_plantName_5.setStyleSheet("color: rgb(203, 255, 205);\n"
"background-color: rgb(10, 112, 64);\n"
"border-radius:10px;")
        self.label_plantName_5.setTextFormat(QtCore.Qt.AutoText)
        self.label_plantName_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label_plantName_5.setObjectName("label_plantName_5")
        self.Capture_2 = QtWidgets.QPushButton(self.centralwidget)
        self.Capture_2.setGeometry(QtCore.QRect(180, 450, 51, 51))
        self.Capture_2.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(12)
        self.Capture_2.setFont(font)
        self.Capture_2.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.Capture_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Capture_2.setStyleSheet("\n"
"QPushButton::hover\n"
"{\n"
"background-color: rgb(10, 112, 64);\n"
"};\n"
"background-color: rgb(45, 136, 66);\n"
"color: rgb(0, 170, 127);\n"
"color:#9DDABC;\n"
"border-radius: 25px;")
        self.Capture_2.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/img1/translating.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Capture_2.setIcon(icon4)
        self.Capture_2.setIconSize(QtCore.QSize(40, 40))
        self.Capture_2.setObjectName("Capture_2")
        self.label_plantName_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_plantName_6.setGeometry(QtCore.QRect(10, 29, 201, 201))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Book")
        font.setPointSize(11)
        self.label_plantName_6.setFont(font)
        self.label_plantName_6.setAutoFillBackground(False)
        self.label_plantName_6.setStyleSheet("color: rgb(203, 255, 205);\n"
"background-color: rgb(10, 112, 64);\n"
"")
        self.label_plantName_6.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_plantName_6.setObjectName("label_plantName_6")
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(-20, 540, 961, 16))
        self.frame_4.setStyleSheet("background-color: rgb(10, 112, 64);\n"
"border-radius:10px;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.frame_2.raise_()
        self.frame_3.raise_()
        self.frame.raise_()
        self.frame_5.raise_()
        self.label_2.raise_()
        self.viewLocatio.raise_()
        self.predictImage.raise_()
        self.InsertImage.raise_()
        self.label_plantName_3.raise_()
        self.label_plantName.raise_()
        self.label_plantName_4.raise_()
        self.Capture.raise_()
        self.label_plantName_2.raise_()
        self.label_plantName_5.raise_()
        self.scrollArea.raise_()
        self.Capture_2.raise_()
        self.label_plantName_6.raise_()
        self.label_image.raise_()
        self.frame_4.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Home"))
        self.viewLocatio.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#9ddabc;\">VIEW LOCATION</span></p></body></html>"))
        self.predictImage.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#9ddabc;\">CLASSIFY IMAGE</span></p></body></html>"))
        self.predictImage.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.InsertImage.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#a3e2c3;\">UPLOAD IMAGE</span></p></body></html>"))
        self.Capture.setToolTip(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Microsoft Tai Le\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600; color:#9ddabc;\">CAPTURE PLANTS</span></p></body></html>"))
        self.label_plantName.setText(_translate("MainWindow", "No Image Inserted"))
        self.label_plantName_3.setText(_translate("MainWindow", "Plant Name"))
        self.label_plantName_2.setText(_translate("MainWindow", "Southern Leyte Endemic Herbal Plant Identification"))
        self.label_plantName_5.setText(_translate("MainWindow", "Plant Benefits   "))
        self.Capture_2.setToolTip(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Microsoft Tai Le\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Translate</p></body></html>"))
        self.label_plantName_6.setText(_translate("MainWindow", "Plant Image"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
